config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ideas#index'


  resources :ideas , shallow: true do

   resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy] 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Idea do |i|
      i.user == user
    end

    can :manage, Review do |r|
      r.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :reviews, lambda { order(created_at: :desc) }, dependent: :destroy
  belongs_to :user

  validates(:title, { presence: { message: 'must be given!' },
                    uniqueness: true })
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates :body, presence: true, length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, lambda { order(created_at: :desc) }, dependent: :destroy
  has_many :ideas, lambda { order(created_at: :desc) }, dependent: :destroy

  has_secure_password

  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: true,
                    format: VALID_EMAIL_REGEX

  private

  def downcase_email
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
  redirect_to new_session_path, alert: 'please sign in' unless user_signed_in?
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    User.find session[:user_id] if user_signed_in?
  end
  helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
 before_action :authenticate_user!, except: [:show, :index]

 before_action(:find_idea, { only: [:show, :edit, :destroy, :update] })
 before_action :authorize, only: [:edit, :destroy, :update]

def new
 if user_signed_in?
   @idea = Idea.new
   render :new
 else
   render :new_session_path
 end
end

def create
  @idea  = Idea.new(idea_params)
  @idea.user = current_user
  if @idea.save
    flash[:notice] = 'Idea created successfully'
    redirect_to idea_path(@idea)
  else
    flash.now[:alert] = 'Please fix errors below'
    render :new
  end
end

def show
  @idea = Idea.find params[:id]
  @review = Review.new
end

def index
  @idea = Idea.new
  @ideas = Idea.order(created_at: :desc)
end

def edit
  if current_user != @idea.user
    redirect_to root_path, alert: 'Not authorized'
  end
end

def update
  if @idea.update idea_params
    redirect_to idea_path(@idea), notice: 'Idea updated!'
  else
    render :edit
  end
end

def destroy
  @idea.destroy
  redirect_to ideas_path, notice: 'Idea deleted!'
end

private

def idea_params
  # this feature is called strong parameters (introduced in Rails 4+)
  params.require(:idea).permit([:title, :description])
end

def find_idea
  @idea = Idea.find params[:id]
end

def authorize
  if cannot?(:manage, @idea)
  redirect_to root_path, alert: 'Not authorized!'
  end
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    review_params = params.require(:review).permit(:body)
    @review = Review.new review_params
    @idea = Idea.find params[:idea_id]
    @review.user = current_user
    @review.idea = @idea
    if @review.save
      redirect_to idea_path(params[:idea_id]), notice: 'Review created!'
    else
      flash[:alert] = 'please fix errors'
      render 'ideas/show'
    end
  end

  def destroy
    review = Review.find params[:id]
    review.destroy
    redirect_to idea_path(review.idea_id), notice: 'Review deleted!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Signed in!'
    else
      flash.now[:alert] = 'Wrong credentials'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name,
                                               :email,
                                               :password,
                                               :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      # login the user
      redirect_to root_path, notice: 'Account created successfully!'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<p><%= @idea.errors.full_messages.join(', ') %></p>
<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<button type="button modal-button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  New Idea
</button>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Idea</h4>
      </div>
      <div class="new-idea">
        <p><%= @idea.errors.full_messages.join(', ') %></p>
        <%= form_for @idea do |f| %>
          <div>
            <%= f.label :title %>
            <%= f.text_field :title %>
          </div>
          <div>
            <%= f.label :description %>
            <%= f.text_area :description %>
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-default"><%= f.submit %></button>
          <%# f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="idea-list">
  <hr>
<% @ideas.each do |i| %>
<div class="idea">
  <h4><%= link_to i.title, idea_path(i) %></h4>
  <p><%= i.description %></p>
  <% if i.user_id %>
    <h5>By: <%= User.find(i.user_id).name %></h5>
  <% else %>
    <h5>By: Guest User</h5>
  <% end %>
</div>
<hr>
<% end %>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p><%= @idea.description %></p>
<% if @idea.user_id %>
  <h2><%= User.find(@idea.user_id).name %></h2>
<% else %>
  <h2>Guest User</h2>
<% end %>

<% if can?(:manage, @idea) %>
<%= link_to 'Edit', edit_idea_path(@idea) %>
<%= link_to 'Delete', idea_path(@idea),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
<% end %>

<hr>
<h2>Reviews</h2>
<h3>Review This Idea</h3>



<%= @review.errors.full_messages.join(', ') %>
<%= form_for [@idea, @review] do |f| %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

<hr>
<% @idea.reviews.each do |review| %>
  <%= review.body %>
  <% if can?(:manage, review) %>
    <%= link_to 'delete', review_path(review) ,
                          method: :delete,
                          data: { confirm: 'Are you sure? '} %>
    <% end %>
  <% if review.user_id %>
    <h5><%= User.find(review.user_id).name %></h5>
  <% else %>
    <h5>Guest User</h5>
  <% end %>
  <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <style>
    .logo {
      float: left;
      padding: 15px;
    }
    .leftnav {
      float: right;
      padding: 40px 15px 15px 15px;
    }
    .btn-lg, .btn-group-lg > .btn {
      float: right;
      clear: both;
    }
    </style>
  </head>


  <body>
    <div>
    <a class="logo" href="/"> <h3>Idea Factory</h3></a>

    <div class="leftnav">
  <% if user_signed_in? %>
    <span>Hello <%= current_user.name %> </span>
    <%= link_to "Sign out", session_path(:user_id), :method => :delete %>
  <% else %>
    <%= link_to 'Sign Up', new_user_path %>
    <%= link_to 'Sign In', new_session_path %>
  <% end %>
</div>
</div>
  <%= notice || alert %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= @user.errors.full_messages.join(', ') %>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit 'Sign Up' %>
<% end %>